# Generated by Django 3.0.5 on 2020-05-26 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200524_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 18, 25, 46, 107657, tzinfo=utc)),
        ),
    ]
