# Generated by Django 3.0.5 on 2020-06-21 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200616_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 6, 37, 58, 16118, tzinfo=utc)),
        ),
    ]
