# Generated by Django 3.0.5 on 2020-06-24 17:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200623_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitle',
            old_name='subtitle',
            new_name='subs',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtitle', to='blog.SubTitle'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 11, 42, 951220, tzinfo=utc)),
        ),
    ]
