# Generated by Django 3.0.5 on 2020-06-24 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200624_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 18, 10, 42, 187414, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtitle', to='blog.Subtitle'),
        ),
    ]
